all:
	#g++	-o Dijkstra_test Dijkstra_test.cpp -std=c++17
	g++	-o readFile_test read_from_file.cpp streamInit.cpp r_file_w_console.cpp -std=c++17
clean:
	#rm -f Dijkstra_test
	rm -f readFile_test
run:all
	#./Dijkstra_test
	./readFile_test